<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mechanics.Auth.Application\Mechanics.Auth.Application.csproj"/>
    <ProjectReference Include="..\Mechanics.Auth.Infra.Data\Mechanics.Auth.Infra.Data.csproj"/>
    <ProjectReference Include="..\Mechanics.Auth.Infra.SecretProvider\Mechanics.Auth.Infra.SecretProvider.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
</Project>
