name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
    branches:
      - main
      - release
      - develop

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  tests:
    name: Run tests
    uses: FIAP-POS-TECH-13SOAT-MECHANICS/mechanics-infra/.github/workflows/dotnet-tests.yml@main

  resolve-environment:
    name: Resolve environment name
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.resolve.outputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Resolve Environment
        id: resolve
        uses: FIAP-POS-TECH-13SOAT-MECHANICS/mechanics-infra/.github/actions/resolve-environment@main

  deploy:
    name: Deploy on AWS Lambda
    needs:
      - tests
      - resolve-environment
    uses: FIAP-POS-TECH-13SOAT-MECHANICS/mechanics-infra/.github/workflows/deploy-lambda.yml@main
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      project_path: ./src/Mechanics.Auth.Api
      function_name: fiap-mechanics-${{ needs.resolve-environment.outputs.environment }}-auth-token
    secrets: inherit

  seed:
    name: Seed DynamoDB
    needs:
      - resolve-environment
    uses: ./.github/workflows/seed.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      seeds_path: ./seeds
      service_name: auth
    secrets: inherit
